name: workflow_demo

on:
  pull_request:
    branches:
      - main

jobs:
  job:
    runs-on: aliyun
    steps:
      - run: echo "${{ github.sha }}"
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.ref_name }}"