name: Reuseable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        default: ""
      age:
        type: number
        default: 18
    secrets:
      TOKEN:
        required: true
        type: string
jobs:
  job:
    runs-on: aliyun
    steps:
      - run: |
          echo "name: ${{ inputs.name }}"
          echo "age: ${{ inputs.age }}"
          echo "token: ${{ secrets.TOKEN }}"