name: Reuseable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        default: ""
      age:
        type: number
        default: 18
    secrets:
      USER_PASSWORD:
        required: true
jobs:
  job:
    runs-on: aliyun
    steps:
      - name: job exec
        run: |
          echo "name: ${{ inputs.name }}"
          echo "age: ${{ inputs.age }}"
          echo "token: ${{ secrets.USER_PASSWORD }}"
