name: Reuseable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        default: ""
      age:
        type: number
        default: 18
    secrets:
      USER_PASSWORD:
        required: true
    outputs:
      person_info:
        description: "person info"
        value: ${{ jobs.person_info.outputs.person_info }}
jobs:
  job:
    runs-on: aliyun
    steps:
      - name: person_info job
        id: person_info
        run: echo "person_info = ${{ inputs.name }} - ${{ inputs.age }}" >> $GITHUB_OUTPUT