name: workflow-demo

on: pull_request

jobs:
  build:
    runs-on: aliyun
    container:
      image: ubuntu:latest
    services:
      dind:
        image: docker:dind
        # 通过 options 传递特权模式参数
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Test Docker
        run: |
          docker version
          docker info
