name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    container:
      image: docker:dind
      options: --privileged
    steps:
      - name: Docker Info
        run: docker info