name: Workflow Demo

on: pull_request

jobs:
  job1:
    runs-on: aliyun
    outputs:
      dataSource: ${{ steps.get_data.outputs.dataSource }}
    env:
      name: test
    steps:
      - id: get_data
        run: echo "dataSource={name:${{ env.name }}}" >> $GITHUB_OUTPUT

  job2:
    runs-on: aliyun
    needs: job1
    steps:
      - run: echo "${{fromJSON(toJSON(needs.job1.outputs.dataSource)).name}}"
      - run: echo "${{toJSON(needs.job1.outputs.dataSource)}}"