name: Workflow Demo

on: pull_request

jobs:
  # call-workflow:
  #   uses: ./.github/workflows/reuseable-workflow.yaml
  #   with:
  #     name: "test"
  #     age: 18
  #   secrets: inherit
  call-workflow-outputs:
    # needs: call-workflow
    runs-on: aliyun
    env:
      D1: ${{ toJSON({"name": "test", "age": "18"}) }}
    steps:
      - id: info
        run: echo $D1