name: Workflow Demo

on: pull_request

jobs:
  call-workflow:
    uses: ./.github/workflows/reuseable-workflow.yaml
    with:
      name: test
      age: 18
    secrets: inherit
  call-workflow-outputs:
    runs-on: aliyun
    needs: call-workflow
    steps:
      - run: echo ${{ fromJSON(needs.call-workflow.outputs.person_info) }}
