name: workflow-demo

on: pull_request

jobs:
  build:
    runs-on: aliyun
    container:
      image: docker:24.0.6  # 使用与宿主机兼容的Docker客户端版本
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  # 挂载套接字
    steps:
      - name: Docker Info
        run: docker info