name: Workflow Demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    container:
      image: node:20-alpine
      env:
        NODE_ENV: development
    steps:
      - run: echo "Hello, world!"