name: Workflow Demo

on: pull_request

jobs:
  call-workflow:
    uses: ./.github/workflows/reuseable-workflow.yaml
    with:
      name: "test"
      age: 18
    secrets: inherit
  call-workflow-outputs:
    needs: call-workflow
    runs-on: aliyun
    steps:
      - id: info
        run: echo "${{ fromJSON('{"name":"xxx"}').name }}"