name: Workflow Demo

on: pull_request

jobs:
  call-workflow:
    uses: ./.github/workflows/reuseable-workflow.yaml
    with:
      name: "test"
      age: 18
    secrets: inherit
  call-workflow-outputs:
    needs: call-workflow
    runs-on: aliyun
    env:
      INFOAB: ${{ toJSON({name: "GitHub") }}
    steps:
      - id: info
        env:
          DATA: ${{ env.INFOAB.name}}
        run: echo $INFOAB