name: Workflow Demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
      app:
        image: ubuntu:latest
        command: ping mysql
    steps:
      - run: echo "Hello, world!"
