name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    container:
      image: docker:28.2.2-dind-alpine3.22
      options: --privileged --volume=/var/lib/docker.sock:/var/lib/docker.sock
    steps:
      - name: OS Info
        run: cat /etc/os-release
      - name: Docker Version
        run: docker -v
      - name: Docker List
        run: docker ps & docker images
