name: Workflow Demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    services:
      dind:
        image: docker:dind
        privileged: true
      steps:
       - name: Build image
         run: |
          docker build -t myapp .