name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    container:
      image: docker:28.2.2-dind-alpine3.22
    steps:
      - name: Docker Pull
        run: docker pull nginx:latest
      - name: Docker List
        run: docker ps