name: Workflow Demo

on: pull_request

jobs:
  job0:
    runs-on: aliyun
    steps:
      - run: docker -v
  job:
    runs-on: aliyun
    container:
      image: docker:dind
    steps:
      - run: docker -v
