name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    container:
      image: docker:dind
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: npm run build
      - name: Build Docker Image
        run: docker build -t my-web-app .
      - name: List images
        run: docker images