name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    container:
      image: docker:28.2.2-dind-alpine3.22
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
      options:
        --privileged
    steps:
      - name: OS Info
        run: cat /etc/os-release
      - name: Docker Info
        run: docker info