name: workflow-demo

on: pull_request

jobs:
  build:
    runs-on: aliyun
    container:
      image: ubuntu:latest
    steps:
      - name: Install Docker
        run: |
          apt-get update
          apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Test Docker
        run: |
          docker version
          docker info
