name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    container:
      image: docker:dind
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  # 关键挂载
    steps:
      - name: Docker Info
        run: docker info