name: Workflow Demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    services:
      nginx:
        image: nginx:latest
    container:
      image: ubuntu:latest
    steps:
      - run: apt-get install curl
      - run: curl nginx

#
