name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    steps:
      - name: greeting
        run: echo "Hello, World!"
      - name: ls
        run: |
          ls /_work
          ls /_work/_temp


