name: workflow-demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    services:
      dind:
        image: docker:dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""  # 禁用TLS
    steps:
      - name: Set up Docker
        run: |
          echo "DOCKER_HOST=tcp://dind:2375" >> $GITHUB_ENV
          docker info  # 测试连接

#1