name: workflow-demo

on: pull_request

jobs:
  build:
    runs-on: aliyun
    container:
      image: ubuntu:latest
    services:
      dind:
        image: docker:dind
        # 通过 options 传递特权模式参数
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""  # 禁用 TLS（仅限可信网络）
    steps:
      - name: Docker Info
        env:
          DOCKER_HOST: tcp://dind:2375
        run: docker info
