name: Workflow Demo

on: pull_request

jobs:
  job1:
    runs-on: aliyun
    outputs:
      dataSource: ${{ steps.get_data.outputs.dataSource }}
    steps:
      - id: get_data
        run: echo "dataSource={}" >> $GITHUB_OUTPUT

  job2:
    runs-on: aliyun
    needs: job1
    steps:
      - run: echo "${{needs.job1.outputs.dataSource}}"