name: Workflow Demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
    container:
      image: alpine:latest
    steps:
      - run: cat /etc/os-release
      - run: apk add mysql-client
      - run: mysql -h mysql -u root -ppassword -e "SELECT 1"
