name: Workflow Demo

on: pull_request

jobs:
  job:
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - run: mysql -h mysql -u root -ppassword -e "SELECT 1"