name: workflow-demo

on: pull_request

jobs:
  build:
    runs-on: aliyun
    services:
      dind:
        image: docker:dind
        # 通过 options 传递特权模式参数
        options: --privileged
    steps:
      - run: docker info
        env:
          DOCKER_HOST: tcp://dind:2375